# Generated by Django 4.2.11 on 2024-07-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_task_options_remove_task_completed_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
